server:
  port: 8080
  servlet:
    context-path: /identity
jwt:
  signer-key: LnnRceIhXhXxOTcWPOPS3XfZF//VpFUC9GuB0NuNOkHZ3F1iWWNRzDRREY0hTBRJ+nAHTX+P9grOGN6ZM6LMug==
  valid-duration: 3600 #seconds
  #  valid-duration: 10 #seconds
  refreshable-duration: 3600 #seconds

spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:postgresql://192.168.1.251:5432/test
    username: jiag
    password: 20053331
    driver-class-name: org.postgresql.Driver
    dbcp2:
      default-schema: identity_service
    hikari:
      schema: identity_service

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true #Ngan insert data sql truoc khi jpa duoc tao
  data:
    redis:
      host: 192.168.1.251
      port: 6379
      username: jiag
      password: 20053331
      ttl: 1 #days
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  sql:
    init:
      mode: always
      data-locations: classpath:database/data_indentity_service.sql #insert data
      schema-locations: classpath:database/schema_identity_service.sql #tao schema
  kafka:
    bootstrap-servers: 192.168.1.251:9092
    listener:
      missing-topics-fatal: false
    consumer:
      group-id: identity-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
