server:
  port: 8081
  servlet:
    context-path: /jobtify
spring:
  application:
    name: jobtify-service
  datasource:
    url: jdbc:postgresql://192.168.1.251:5432/test #CẦN THAY ĐỔI
    username: jiag #CẦN THAY ĐỔI
    password: 20053331 #CẦN THAY ĐỔI
    driver-class-name: org.postgresql.Driver
    dbcp2:
      default-schema: jobtify_service
    hikari:
      schema: jobtify_service}
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_schema: jobtify_service
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true #Ngan insert data sql truoc khi jpa duoc tao
  sql:
    init:
      mode: always
      data-locations: classpath:database/data_jobtify_service.sql #insert data
      schema-locations: classpath:database/schema_jobtify_service.sql #tao schema
  kafka:
    bootstrap-servers: 192.168.1.251:9092 #CẦN THAY ĐỔI
    consumer:
      group-id: jobtify-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
