server:
  port: 8088
app:
  api-prefix: /api/v1
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: jobtify-service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/jobtify/**
          filters:
            - StripPrefix=2
        - id: elastic-search-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/elastic-search/**
          filters:
            - StripPrefix=2
